Linkedin signin
oleksiizd/nextjs-task pull request #1
Opened 2021-07-08 08:45 UTC by oleksiizd

2021-07-08 10:10 UTC, dmytro-devima-solutions requested changes

2021-07-08 10:10 UTC, dmytro-devima-solutions commented on pages/index.tsx
> +        <a href="https://www.linkedin.com/oauth/v2/authorization?response_type=code&state=123&scope=r_liteprofile&client_id=785jez5b2sszz3&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fcardpage">
Та сама проблема з redirect_uri що і вище

2021-07-12 08:25 UTC, dmytro-devima-solutions commented on pages/card.tsx
> +  answerr: IAnswerType;
`answerr` -> `answer`

2021-07-12 08:25 UTC, dmytro-devima-solutions commented on tsconfig.json
> +    "strict": false,
Чому поміняв назад на false?

2021-07-12 08:25 UTC, dmytro-devima-solutions commented on components/types.ts
> +export interface IAccessToken {
axios має інтерфейс `AxiosResponse`, ти можеш його використати замість того щоб описувати свій

2021-07-15 07:28 UTC, DevimaSolutions requested changes

2021-07-15 07:28 UTC, DevimaSolutions commented on components/404Comp/index.tsx
> +    <ThemeProvider theme={theme}>
У _app.tsx вже є провейдер, не потрібно його ще раз підключати

2021-07-15 07:28 UTC, DevimaSolutions commented on components/404Comp/index.tsx
> +  type Anchor = "right";
Типи не оголошують всередині компонента

2021-07-15 07:28 UTC, DevimaSolutions commented on components/404Comp/index.tsx
> +  const errorStyles = useStyles();
Зазвичай цю змінну називають  classes

2021-07-15 07:28 UTC, DevimaSolutions commented on components/404Comp/index.tsx
> +    (anchor: Anchor, open: boolean) =>
Навіщо через кпуп функцій передавати змінну anchor, якщо вона у тебе завжди є константою

2021-07-15 07:28 UTC, DevimaSolutions commented on components/404Comp/index.tsx
> +  const [state, setState] = React.useState({
Навіщо тобі тут стільки полів, якщо ти використовуєш тільки `right`?

2021-07-15 07:28 UTC, DevimaSolutions commented on components/404Comp/index.tsx
> +  const list = (anchor: Anchor) => (
Уикористай тут `useMemo` замість функції

2021-07-15 07:28 UTC, DevimaSolutions commented on components/404Comp/index.tsx
> +            href="http://localhost:3000/"
Це має бути next/link. І не використовуй абсолютні шляхи в середині сайту (`http://localhost:3000/` => `/`)

2021-07-15 07:28 UTC, DevimaSolutions commented on components/404Comp/index.tsx
> +                  <Image src={DiscordLogo} alt="Discord logo" />
Використовуй відносні лінки замість імпорту зображень

2021-07-15 07:28 UTC, DevimaSolutions commented on components/404Comp/styles.ts
> +    backgroundSize: "cover",
```
backgroundImage: "url(/GroupString.svg)",
backgroundRepeat: "no-repeat",
backgroundPosition: "center",
backgroundSize: "cover",
```
Можна описати одним `background`

2021-07-15 07:28 UTC, DevimaSolutions commented on components/404Comp/styles.ts
> +    marginLeft: "25px",
```
marginTop: "23px",
marginBottom: "23px",
marginLeft: "25px",
```
Описати через `margin` і так далі, групуй стилі у одну властивість коли можеш

2021-07-15 07:28 UTC, DevimaSolutions commented on components/404Comp/styles.ts
> +    marginTop: "31px",
Замість рядка, значення у пікслелях вказуй просто цифрою, де можливо

2021-07-15 07:28 UTC, DevimaSolutions commented on components/404Comp/styles.ts
> +    [theme.breakpoints.down("xs")]: {
Треба використовувати mobile-first підхід, спочатку стилі для меншого екрану потім брекпойнти `up`.

2021-07-15 07:28 UTC, DevimaSolutions commented on components/CardComp/index.tsx
> +  const { profilePicture, ...rest2 } = rest;
`rest2` ти не використовуєш, не лишай змінні і імпорти які не використовуються

2021-07-15 07:28 UTC, DevimaSolutions commented on pages/_app.tsx
> +MyApp.propTypes = {
propTypes не використовуються у ts

2021-07-15 07:28 UTC, DevimaSolutions commented on pages/index.tsx
> +  return <HomeComp />;
Назви компонентів переглянь. Не додавай `Comp` до назви, і так зрозуміло, що рендериш компонент. Замість цього краще більш детально опиши що це, наприклад `HomePageContent`

2021-07-15 07:28 UTC, DevimaSolutions commented on services/getAccessToken.ts
> +  const pathcard = hostString + "cardpage";
`pathCard` змінні називаємо через caleCase

2021-07-15 07:28 UTC, DevimaSolutions commented on styles/Home.module.css
>    align-items: center;
Заміни на useStyles

2021-07-16 08:28 UTC, DevimaSolutions commented on components/404Comp/Header/header.tsx
> +      onKeyDown={toggleDrawer(false)}
Я б виніс окремо функцію яку ти вішаєш на клік, і яку на кнопки. Тоді код був би більш читабельний

2021-07-16 08:28 UTC, DevimaSolutions commented on components/404Comp/Header/header.tsx
> +          ></Button>
Якщо уконмпоненту немає контенту, тег має відразу закриватись `></Button>` => `/>`

2021-07-16 09:55 UTC, DevimaSolutions commented on components/404Comp/Header/header.tsx
> +    (open: boolean) => (event: React.KeyboardEvent | React.MouseEvent) => {
На клік кнопки не буде тригиритись KeyboardEvent

2021-07-16 09:55 UTC, DevimaSolutions commented on components/404Comp/Header/header.tsx
> +    (open: boolean) => (event: React.KeyboardEvent | React.MouseEvent) => {
A тут у тебе не буде MouseEvent

2021-07-16 09:55 UTC, DevimaSolutions commented on components/404Comp/Header/header.tsx
> +  const list = () => (
Заміни функцію на useMemo

2021-07-19 10:09 UTC, DevimaSolutions commented on components/CardComp/index.tsx
> +  const LastName = data.localizedLastName;
Змінні з великої букви не назвиваємо, запам'ятатй

2021-07-19 10:09 UTC, DevimaSolutions commented on components/CardComp/index.tsx
> +    data.profilePicture["displayImage~"].elements[1].identifiers[0].identifier;
Діставати імедж таким чином потрібно на етапі коли ти отримав респонс у сервісі. У стор вже мають сететись дані у нормальному вигляді

2021-07-19 10:09 UTC, DevimaSolutions commented on pages/_app.tsx
> +  const useInitializedStore = (initialState: IInitState) => {
Не оголошуй хуки в середині компонентів, винеси

2021-07-19 10:09 UTC, DevimaSolutions commented on pages/cardpage.tsx
> +  const reduxStore = initializeStore({});
Зроби щоб у initializeStore параметр був опціональним. Тоді не потібно буде передавати пустий об'єкт

2021-07-19 10:09 UTC, DevimaSolutions commented on redux/store.ts
> +let store: any;
any не використовуємо, опигши нормально тип стору

2021-07-19 10:09 UTC, DevimaSolutions commented on redux/slices/reducer.ts
> +const initialState = {
Оголоси тип для цього стейту, і приведи initialState до нього. Щоб було щось типу
```
const initialState: IUserDataState = {
...
};
```

2021-07-19 10:09 UTC, DevimaSolutions commented on styles/globals.css
> +  color: #ffffff;
css файлів не має бути. Використовуємо makeStyles замість них

2021-07-19 10:09 UTC, DevimaSolutions commented on types/types.ts
> +interface Iidentifiers {
Iidentifiers => IIdentifiers

2021-07-19 10:09 UTC, DevimaSolutions commented on types/types.ts
> +export interface IAnswerType {
Поміняй назви типів, щоб було зрозуміло для чого вони. 
Наприклад 
IAnswerType => ILinkedinUserResponse, 
IData => ILinkedinAuthData 
і так далі

2021-07-19 11:56 UTC, DevimaSolutions commented on components/404Comp/Header/header.tsx
>    const ToggleDrawerKeyDown =
З малої букви змінні. Переглянь по усьому проекту

2021-07-19 11:56 UTC, DevimaSolutions commented on components/404Comp/Header/header.tsx
> +        event.type === "keydown" &&
Ти вішаєшся на keyDown, тут тип завжди буде "keydown"

2021-07-19 11:56 UTC, DevimaSolutions commented on components/404Comp/Header/header.tsx
> +        (event.key === "Tab" || event.key === "Shift")
Можна цю перевірку записати таким чином
`["Tab", "Shift"].includes(event.key)`

2021-07-19 11:56 UTC, DevimaSolutions commented on components/404Comp/Header/header.tsx
> +  }, [isOpen]);
Все ще не залежить

2021-07-19 11:56 UTC, DevimaSolutions commented on redux/hooks/hooks.ts
> +import { IInitialStoreState } from "../../types/types";
Назви файл відповідно до назви хука

2021-07-19 11:56 UTC, DevimaSolutions commented on redux/store.ts
> +const configureStorePreloaded = (preloadedState?: any) => {
Все ще використовується any, перевір всюди

2021-07-19 15:18 UTC, DevimaSolutions approved these changes

2021-07-20 08:05 UTC, merged